package com.auditvault.domain;

import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class AuditEventTest {

    @Test
    void shouldCreateAuditEventSuccessfully() {
        String aggregateId = UUID.randomUUID().toString();
        String aggregateType = "User";
        String eventType = "USER_CREATED";
        Instant timestamp = Instant.now();
        String userId = "admin";
        String payload = "{\"name\":\"John Doe\"}";

        AuditEvent event = AuditEvent.builder()
                .aggregateId(aggregateId)
                .aggregateType(aggregateType)
                .eventType(eventType)
                .timestamp(timestamp)
                .userId(userId)
                .payload(payload)
                .obfuscated(false)
                .build();

        assertNotNull(event.getId()); // Generated by builder if null
        assertEquals(aggregateId, event.getAggregateId());
        assertEquals(aggregateType, event.getAggregateType());
        assertEquals(eventType, event.getEventType());
        assertEquals(timestamp, event.getTimestamp());
        assertEquals(userId, event.getUserId());
        assertEquals(payload, event.getPayload());
        assertFalse(event.isObfuscated());
    }

    @Test
    void shouldThrowExceptionWhenAggregateIdIsNull() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> 
            AuditEvent.builder()
                    .aggregateType("User")
                    .eventType("USER_CREATED")
                    .timestamp(Instant.now())
                    .build()
        );
        assertEquals("aggregateId cannot be null or blank", exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenEventTypeIsNull() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> 
            AuditEvent.builder()
                    .aggregateId(UUID.randomUUID().toString())
                    .aggregateType("User")
                    .timestamp(Instant.now())
                    .build()
        );
        assertEquals("eventType cannot be null or blank", exception.getMessage());
    }

    @Test
    void shouldThrowExceptionWhenTimestampIsNull() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> 
            AuditEvent.builder()
                    .aggregateId(UUID.randomUUID().toString())
                    .aggregateType("User")
                    .eventType("USER_CREATED")
                    .build()
        );
        assertEquals("timestamp cannot be null", exception.getMessage());
    }
}
