spring.application.name=auditvault
auditvault.snapshot.threshold=50
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always
spring.jpa.open-in-view=false

# Actuator & Observability
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=auditvault

# Resilience4j
resilience4j.circuitbreaker.instances.elasticsearch.sliding-window-size=10
resilience4j.circuitbreaker.instances.elasticsearch.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.elasticsearch.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.elasticsearch.permitted-number-of-calls-in-half-open-state=3
resilience4j.retry.instances.elasticsearch.max-attempts=3
resilience4j.retry.instances.elasticsearch.wait-duration=2s
